refactor(tls): do not generate tls certificate when server starts up
yomorun/yomo pull request #280
Opened 2022-01-25 04:05 UTC by wujunzhuo

@fanweixiao @figroc @venjiang @xiaojian-hong 看一下改的对不对

2022-01-25 05:38 UTC, fanweixiao commented on pkg/tls/tls.go
> +func getDevCertAndKey() ([]byte, []byte) {
share we put this to `.env.local` file?

2022-01-25 05:39 UTC, fanweixiao approved these changes

2022-01-25 06:04 UTC, figroc reviewed
建议还是分离更彻底一点，把生成的代码完全去除

2022-01-25 06:10 UTC, fanweixiao commented on core/client.go
> +			InsecureSkipVerify: len(env) == 0 || env == "development",
@figroc gotcha 👍🏼

2022-01-25 07:07 UTC, fanweixiao commented on core/client.go
> +			InsecureSkipVerify: len(env) == 0 || env == "development",
> 建议还是分离更彻底一点，把生成的代码完全去除

这个咱们是否可以放在 `v2.x` 版本再去改动，因为这个改动会 break 掉已经部署现在这个版本的用户的升级了。

2022-01-26 14:20 UTC, fanweixiao commented
👍🏼  
I suggest we merge this to `v1.7`

2022-01-26 14:25 UTC, fanweixiao requested changes

2022-01-26 14:25 UTC, fanweixiao commented on pkg/tls/tls.go
> +func CreateServerTLSConfig() (*tls.Config, error) {
@wujunzhuo should change comment to `CreateServerTLSConfig create server tls config.`

2022-01-26 14:25 UTC, fanweixiao commented on pkg/tls/tls.go
> +// Create client tls config.
@wujunzhuo should change comment to `CreateClientTLSConfig create client tls config.`

2022-03-02 13:21 UTC, fanweixiao commented on test/tls/generate_key.sh
> +
seems we have to do a lot of documenting job for CA and sort of stuffs to developers. Most of junior developers know little about these.

2022-03-02 13:21 UTC, fanweixiao approved these changes

2022-03-02 14:14 UTC, merged