Fix/cli build
yomorun/yomo pull request #444
Opened 2023-02-07 15:59 UTC by woorui

2023-02-08 03:07 UTC, wujunzhuo approved these changes

2023-02-08 09:29 UTC, venjiang approved these changes

2023-02-08 09:32 UTC, fanweixiao requested changes

2023-02-08 09:32 UTC, fanweixiao commented on README.md
> +	fmt.Printf("[%s] %d > value: %f ⚡️=%dms\n", value.From, value.Time, value.Noise,rightNow-value.Time)
`,rightNow-value.Time` -> `, rightNow-value.Time`, please add a space behind comma

2023-02-10 09:14 UTC, xiaojian-hong approved these changes

2023-02-20 03:43 UTC, fanweixiao approved these changes

2023-02-20 03:43 UTC, merged