fix: server close connection if auth failed
yomorun/yomo pull request #518
Opened 2023-04-25 17:12 UTC by woorui

2023-04-25 17:15 UTC, woorui commented on core/control_stream.go
> +		return md, ss.CloseWithError(
If authentication fails, the server will now close the connection.

2023-04-25 17:15 UTC, woorui commented on core/control_stream.go
> +		if qerr := new(quic.ApplicationError); errors.As(err, &qerr) && qerr.ErrorCode == yerr.ErrorCodeAuthenticateFailed.To() {
The client receives auth failed error here.

2023-04-26 13:54 UTC, fanweixiao requested changes

2023-04-26 13:54 UTC, fanweixiao commented on core/control_stream.go
>  			"yomo: read unexcept frame during waiting authentication resp, frame readed: %s",
```suggestion
			"yomo: read unexpected frame during waiting authentication resp, frame read: %s",
```

2023-04-26 14:15 UTC, fanweixiao approved these changes

2023-04-27 15:35 UTC, merged