add an ai provider: ollama with mistral model
yomorun/yomo pull request #834
Opened 2024-06-06 04:31 UTC by wujunzhuo

# Description

By using the ([Ollama](https://ollama.com) backend provider and MistralAI models, users could build up the function calling system with all open-source deps from zero.

2024-06-11 04:28 UTC, venjiang requested changes

2024-06-11 04:28 UTC, venjiang commented on pkg/bridge/ai/provider/ollama/provider.go
> +	if !strings.HasPrefix(req.Model, "mistral") {
There should be default model name: `mistral`, `/invoke` API will not work.

2024-06-11 07:04 UTC, venjiang commented
Usage needs to be implemented, used by `prompt_eval_count` and `eval_count`, see [ollama API](https://github.com/ollama/ollama/blob/main/docs/api.md)

2024-06-12 11:53 UTC, venjiang approved these changes
👍

2024-06-12 13:03 UTC, fanweixiao approved these changes
🥇

2024-06-14 04:04 UTC, woorui approved these changes

2024-06-14 08:55 UTC, merged