feat: caller supports setting system prompt and its opration
yomorun/yomo pull request #917
Opened 2024-10-10 19:04 UTC by woorui

2024-10-12 03:12 UTC, venjiang requested changes

2024-10-12 03:12 UTC, venjiang commented on pkg/bridge/ai/caller.go
>  // SetSystemPrompt gets the system prompt
```suggestion
// GetSystemPrompt gets the system prompt
```

2024-10-16 01:12 UTC, fanweixiao approved these changes

2024-10-16 01:14 UTC, fanweixiao approved these changes

2024-10-16 01:19 UTC, fanweixiao commented
🥇

2024-10-16 06:48 UTC, venjiang approved these changes

2024-10-16 07:00 UTC, merged